# Generated by Django 5.2.3 on 2025-07-12 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_category_options_alter_event_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'time'], 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='event_images/default_event_image.jpg', null=True, upload_to='event_images/', verbose_name='Event Image'),
        ),
        migrations.AddField(
            model_name='event',
            name='rsvped_users',
            field=models.ManyToManyField(blank=True, related_name='rsvped_events', to=settings.AUTH_USER_MODEL, verbose_name="RSVP'd Participants"),
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
