# Generated by Django 5.2.7 on 2025-10-19 22:57

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_image_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="event_images/",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="profile_pictures/",
            ),
        ),
    ]
