# Generated by Django 5.2.7 on 2025-10-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_rsvp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("valid", "Valid"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rsvp",
            name="status",
            field=models.CharField(
                choices=[
                    ("attending", "Attending"),
                    ("not_attending", "Not Attending"),
                    ("maybe", "Maybe"),
                ],
                default="attending",
                max_length=20,
            ),
        ),
    ]
